# Generated by Django 6.0.5 on 2026-05-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('title', models.CharField(default='Head Dentist', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='dentists/')),
                ('education', models.TextField()),
                ('credentials', models.TextField()),
                ('memberships', models.TextField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('bio', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
