# Generated by Django 6.0.5 on 2026-06-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('education', models.TextField()),
                ('credentials', models.TextField()),
                ('memberships', models.TextField()),
                ('experience', models.TextField()),
                ('profile_image', models.ImageField(upload_to='dentist_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Dentist',
        ),
    ]
