# Generated by Django 6.0.5 on 2026-06-24 10:16

import dentists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0002_dentistprofile_delete_dentist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=dentists.models.upload_to_dentist_profile),
        ),
    ]
