# Generated by Django 6.0.5 on 2026-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('category', models.CharField(choices=[('oral_health', 'Oral Health'), ('whitening', 'Teeth Whitening'), ('kids_dentistry', 'Kids Dentistry'), ('gum_care', 'Gum Care'), ('dental_tips', 'Dental Tips')], max_length=50)),
                ('content', models.TextField()),
                ('author', models.CharField(default='Head Dentist', max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
